### ISSUE TITLE
Son tweetler başlığının altında siyah border görünüyor.

### ISSUE THREAD

**Issue by bilalunalnet** [madebysense/oyk-wp-theme#3]
Son tweetler başlığının altında bir beyaz çizgi var. Bu beyaz çizginin altında ise siyah bir border görünüyor. CSS kuralını incelediğimde bu siyah borderin istenilen bir tasarım olmadığını gördüm.

<img width="415" alt="screen shot 2018-05-29 at 23 02 15" src="https://user-images.githubusercontent.com/7779221/40682679-1ee69230-6395-11e8-9530-c1fb781953e9.png">

**Comment by bilalunalnet** [comment]
şu #2 pull request üzerinde değişiklik incelenebilir.

**Comment by baransomakli** [comment]
Teşekkür ederiz fakat CSS'de !important kullanımı sonradan farklı sorunlar yaratacağı için CSS kurallarına uygun bir şekilde düzenleyip tekrardan yollayacağım.

**Comment by bilalunalnet** [comment]
Evet haklısınız. Kural, eklentinin stil dosyasından geldiğinden dolayı !important kullandım.

**Comment by ugurarici** [comment]
Baran'ın yaptığı değişiklikleri mastera birleştirdim, kapatıyorum (Y)
