### ISSUE TITLE
SSS sayfasindaki sorular horizontal accordion olmali.

### ISSUE THREAD

**Issue by om3rcitak** [madebysense/oyk-wp-theme#4]
SSS sayfasindaki sorular horizontal accordion olmali. Bu sekilde cok kullanissiz. Kullanici bir soruya tikladiginda taa sayfanin ilgili kismina gidiyor.

**Comment by ugurarici** [comment]
Bu gündemimizde, çünkü eskisinden aldık ve  ancak akordiyon olmamalı diye düşünüyoruz, çünkü başvuran herkesin bunları baştan sona okuması lazım. Her soru için aç-kapa muhabbeti çok can sıkıcı oluyor bu durumda

Şu anda bir çözüm üzerinde çalışıyoruz. Bir de şrfsz herif bunu mesaj atsana buraya emir girer gibi OLMALI yazacağına :)) "olabilir" ya da "olsa mı" ya da "olmalı mı??" falan de bari :))
