### ISSUE TITLE
Menü Alan Darlığı

### ISSUE THREAD

**Issue by MuhammetDilmac** [madebysense/oyk-wp-theme#6]
Menü yazı alanı içeriğe nazaran dar kaldığı için menüde ki yazı ikinci satıra geçiyor ve buda kaymaya sebep oluyor.

![Issue](https://image.ibb.co/eDE7No/2018_06_04_11_36_21_ekran_g_r_nt_s.png)

**Comment by baransomakli** [comment]
Teşekkürler, sorunu çözüp dev branch'ine commitledim.

**Comment by ugurarici** [comment]
Bildirim için teşekkürler @MuhammetDilmac 
Eline sağlık @baransomakli
