### ISSUE TITLE
listedeki girintiler sifirlanmis, sifirlanmamali

### ISSUE THREAD

**Issue by om3rcitak** [madebysense/oyk-wp-theme#7]
`button, fieldset, menu, ol, td, ul {padding:0}` diye bir css kodu var. Buradaki secicilerden "ul" kaldirilmali. Zira kurs icerigi sayfasindaki listelerde, alt listeler ile ust listeler hep ayni hizadan baslamis.

![image](https://user-images.githubusercontent.com/5197413/41439371-2c2af616-7033-11e8-97c8-0508de9873be.png)

**Comment by ugurarici** [comment]
Evet bunun gibi çok fazla yanlış var css içinde, hepsini @baransomakli ile konuştuk

Bu ve birkaçı için özel istisnalar yazıldı ama yanlış tabi, bu tip şeyler asla sıfırlanmamalı. Standarta oturtulabilir ancak
